# Generated by Django 3.0.6 on 2020-10-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobileSpecsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('mobile_name', models.CharField(max_length=250)),
                ('specifications', models.CharField(max_length=1500)),
                ('image_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
