# Generated by Django 3.0.6 on 2020-11-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='comprare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=250)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mobileSpecsLink')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserData')),
            ],
        ),
    ]
