# Generated by Django 3.0.6 on 2020-11-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comprare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comprare',
            new_name='compare',
        ),
    ]
