# Generated by Django 3.0.6 on 2020-11-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201102_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='mobile_name',
        ),
    ]
