# Generated by Django 3.0.6 on 2020-11-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mobileSpecsLink')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserData')),
            ],
        ),
    ]
