# Generated by Django 3.0.6 on 2020-11-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201120_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='mobile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.mobileSpecsLink'),
            preserve_default=False,
        ),
    ]
