# Generated by Django 3.0.6 on 2020-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_devicedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetails',
            name='price',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilespecslink',
            name='price',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
