# Generated by Django 3.0.6 on 2020-12-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201216_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.deviceDetails'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.deviceDetails'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.deviceDetails'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.deviceDetails'),
        ),
    ]
